# Theme configuration
theme: just-the-docs

# Enable required plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

# Configuration for relative links
relative_links:
  enabled: true
  collections: true

# Base URL if your site is hosted in a subdirectory
baseurl: "https://kevaldekivadiya2415.github.io/textembed"

# SEO and Sitemap settings
seo:
  title: "Your Project Documentation"
  description: "Comprehensive documentation for the TextEmbed."
  url: "https://kevaldekivadiya2415.github.io/textembed"

sitemap:
  exclude:
    - /tag/
    - /category/
    - /page/
    - /feed.xml

# Pagination settings for documentation
paginate: 10
paginate_path: "/page:num/"

# Navigation settings
# Navigation for Just the Docs theme
nav:
  - title: "Home"
    url: "/"
  - title: "Setup"
    url: "/setup/"
  - title: "Swagger"
    url: "/swagger/"
  - title: "Search"
    url: "/search/"
  - title: "GitHub"
    url: "https://github.com/kevaldekivadiya2415/textembed"

# Sidebar configuration
# For Just the Docs, it has built-in sidebar functionality
sidebar:
  - title: "Documentation"
    items:
      - title: "Getting Started"
        url: "/index/"
      - title: "Setup"
        url: "/setup/"
      - title: "API Documentation"
        url: "/swagger/"
      - title: "Search"
        url: "/search/"

# Version-wise documentation
collections:
  versions:
    output: true
    permalink: /:collection/:path/