site_name: TextEmbed
site_url: https://kevaldekivadiya2415.github.io/textembed/
repo_url: https://github.com/kevaldekivadiya2415/textembed/
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
extra:
  version:
    provider: mike

plugins:
   - swagger-ui-tag:
        background: White
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
