name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (optional)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Extract release tag from event
        if: github.event_name == 'release'
        id: extract_release_tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set release tag from input
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag != ''
        run: echo "RELEASE_TAG=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --tag ${{ secrets.DOCKER_USERNAME }}/textembed:latest --output=type=docker .

      - name: Tag Docker image with release tag
        if: env.RELEASE_TAG
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/textembed:latest ${{ secrets.DOCKER_USERNAME }}/textembed:${{ env.RELEASE_TAG }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/textembed:latest

      - name: Push Docker image with release tag
        if: env.RELEASE_TAG
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/textembed:${{ env.RELEASE_TAG }}
